import type { Metadata } from "next";
import { LegalPage } from "../_components/LegalPage";

export const metadata: Metadata = {
  title: "Terms & Conditions — Luna Stories",
  description: "The terms that apply when you use Luna Stories.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms & Conditions" updated="May 22, 2026">
      <p>
        These terms apply when you use Luna Stories (the iOS app and this
        website), operated by Cortex Lumora. By creating an account or using
        the service, you agree to them.
      </p>

      <h2>Who can use Luna Stories</h2>
      <p>
        Luna Stories is for parents and guardians who want to create bedtime
        stories with and for their children. You must be at least 18 years
        old to create an account.
      </p>

      <h2>Your account</h2>
      <p>
        Keep your sign-in credentials private and let us know right away if
        you suspect someone else has accessed your account. You&apos;re
        responsible for what happens under your account.
      </p>

      <h2>Subscriptions and billing</h2>
      <ul>
        <li>
          Some features are available only with an active Luna Pro
          subscription, purchased through Apple&apos;s in-app purchase system.
        </li>
        <li>
          Payment is charged to your Apple ID. Subscriptions renew
          automatically until cancelled.
        </li>
        <li>
          You can cancel anytime from your Apple ID&apos;s Subscriptions
          settings. Cancellation takes effect at the end of the current
          billing period.
        </li>
        <li>
          Refunds are handled by Apple under their refund policy.
        </li>
      </ul>

      <h2>Content you create</h2>
      <p>
        Characters, story prompts, and any other input you provide are yours.
        You grant us a limited license to process that input so we can
        generate and store the resulting stories and audio for you.
      </p>

      <h2>Stories generated by Luna Stories</h2>
      <p>
        Stories and audio are generated by AI models based on your inputs.
        We curate the experience for bedtime — gentle pacing, age-appropriate
        themes — but AI output isn&apos;t perfect. Please skim a story before
        playing it to your child if you&apos;d like to. The generated content is
        provided for your personal, non-commercial use.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>
          Don&apos;t use Luna Stories to generate content that&apos;s harmful,
          hateful, sexual, or unlawful.
        </li>
        <li>
          Don&apos;t attempt to reverse-engineer, abuse, or interfere with the
          service.
        </li>
        <li>
          Don&apos;t share your account or use it on behalf of someone else
          without their permission.
        </li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate these rules.
      </p>

      <h2>Service changes</h2>
      <p>
        We&apos;re a small team and the app will keep evolving. We may change,
        add, or remove features. If we make a material change to these
        terms, we&apos;ll notify you in the app or by email.
      </p>

      <h2>Disclaimer and liability</h2>
      <p>
        Luna Stories is provided &quot;as is.&quot; To the fullest extent allowed by
        law, Cortex Lumora isn&apos;t liable for indirect, incidental, or
        consequential damages arising from your use of the service. Nothing
        in these terms limits any rights you have that can&apos;t be limited
        under the law where you live.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Email{" "}
        <a href="mailto:cortexlumora@gmail.com">cortexlumora@gmail.com</a>.
      </p>
    </LegalPage>
  );
}
